#!/bin/sh

# Neovim
[ -x "$(command -v nvim)"   ] \
    && alias       \
        vi="nvim"  \
        vim="nvim" \
        view="nvim -R"
# fd as packaged on Ubuntu/Pop!_OS
[ -x "$(command -v fdfind)" ] \
    && alias fd="fdfind"

# System
alias \
    ..="cd .." \
    c="cd"     \
    f="fff"    \
    l="ls"     \
    ll="ls -l" \

# Git
alias \
    gb="git branch" 	    \
    gbd="git branch -D"     \
    gs="git status --short" \
    gss="git status"	    \
    gd="git diff" 	        \
    gds="git diff --stat"   \
    glm="git log master.."  \

# CLIs
alias \
    dri="docker image rm"   \
    dls="docker image ls"   \
    tshark="tshark --color" \
    vh="vagrant halt"       \
    vs="vagrant ssh"        \
    vsu="vagrant up && vagrant ssh"

