#!/bin/sh

helpme() {
    # Run GNU Bash's `help' builtin
    usage="Usage: helpme [-d] <cmd>"
    ! type "bash" >/dev/null && echo "GNU Bash is not installed" && return 1
    [ -z "$1" ] && echo "$usage" && return 1
    [ "$SHELL" = /bin/bash ] && help "$1" && return 0

    if [ "$1" = "-d" ]; then
        if [ -n "$2" ]; then
            bash -c "help -d $2"
        else
            echo "$usage" && return 2
        fi
    else
        bash -c "help $1"
    fi

    return 0
}

pp() {
    # Pretty print file as if it was viewed in a text editor
    usage="Usage: pp <file>"
    [ -z "$1" ] && echo "$usage" && return 1
    cat "$1" | awk '{ print NR "\t" $0 }'
    return 0
}
